# docs - https://starship.rs/config/

[battery]
full_symbol = "🔋  "
charging_symbol = "⚡️  "
discharging_symbol = "💀  "

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[cmd_duration]
min_time = 500
