[battery]
full_symbol = "🔋  "
charging_symbol = "⚡️  "
discharging_symbol = "💀  "

[character]
symbol = "➜"

[cmd_duration]
min_time = 500

# [time]
# disabled = false
# format = "🕙[ %T ]"
# utc_time_offset = +10
