name: Lint
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Shellcheck & Shell Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: 'echo "lint config files"'
