name: Lint
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  fish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ludeeus/action-shellcheck@master
        with:
          scandir: "./home/.config/fish/"
          shell: fish

  shell_scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - run: scripts/lint.bash

  github_actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check workflow files
        uses: docker://rhysd/actionlint:1.6.24
        with:
          args: -color
